### ISSUE TITLE
Mod is not working or something conflicting it(?)

### ISSUE THREAD

**Issue by TotoReste** [StupidRepo/CameraON#6]
The camera still sets off in 5 seconds even I set the value to 0-15

The mods I have:
-Virality
-MyceliumNetworking
-FoundFootage
-LongerSprinting
-ContentSettings
-PerformanceSettings
-RagdollAnywhere
-ConfigSync

Maybe ConfigSync conflicts with the mod but I'm not sure

**Comment by StupidRepo** [comment]
Either ConfigSync, Virality or FoundFootage could be messing with it. I'd assume it's Virality because that most likely patches something in the camera.

Unfortunately, this isn't a problem with me but with Harmony/MMHook.
